language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
notifications:
  email: false
after_success:
  - julia -e 'ENV["TRAVIS_JULIA_VERSION"] != "1.1" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
